id: AEB318C5B
title: f08E5
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:22:25.012724
  last_modified_at: 2022-05-27 15:22:25.012733
